apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: rb63a9n2z-dotnet-basic
  janus-idp.io/tekton: rb63a9n2z-dotnet-basic
  backstage.io/kubernetes-id: rb63a9n2z-dotnet-basic
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: rb63a9n2z-dotnet-basic
resources:
- deployment.yaml
- route.yaml
- service.yaml
